import Banner from '@/components/ui/home/banner';
import ClientReviews from '@/components/ui/home/client-reviews';
import FAQ from '@/components/ui/home/faq';
import Plans from '@/components/ui/home/plans';
import RecentBlogs from '@/components/ui/home/recent-blogs';
import UpcomingEvents from '@/components/ui/home/upcoming-events';
import WhatWeProvide from '@/components/ui/home/what-we-provide';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Home Page',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <main>
      <Banner />
      <Plans />
      <UpcomingEvents />
      <WhatWeProvide />
      <ClientReviews />
      <FAQ />
      <RecentBlogs />
    </main>
  );
}
