import Banner from '@/components/ui/banner';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Home Page',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <main>
      <Banner />
    </main>
  );
}
